### updates existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Sopho Gurjishvili updated",
  "email": "sopho@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1997-01-27"
}

###